AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Rakefile'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20
